apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hello-dev
  namespace: stg
spec:
  interval: 1m
  chart:
    spec:
      chart: hello-world-app 
      version: "1.2.2"
      sourceRef:
        kind: HelmRepository
        name: softonic
        namespace: flux-system
  values: 
    service:
      type: ClusterIP
    replicaCount: 1