apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: dev-apps
  namespace: flux-system
spec:
  interval: 2m
  path: ./clusters/minikube
  prune: true 
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: dev 